version: "3.7"

services:
  node_1:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./micr1:/app
      - ./protobuf/protos:/proto
      - ./protobuf:/protobuf
    command: nest start
    working_dir: /app

  node_2:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./micr2:/app
      - ./protobuf/protos:/proto
      - ./protobuf:/protobuf
    command: nest start
    working_dir: /app
    
  node_client:
    build:
      context: .docker
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - ./protobuf/protos:/proto
      - ./protobuf:/protobuf
    command: nest start
    working_dir: /app
    ports: 
      - 3000:3000
    depends_on: 
      - node_1
      - node_2