FROM node:11-alpine
EXPOSE 3000 6379 50051 8080

RUN npm install -g npm

RUN npm install -g typescript
RUN npm install -g ts-node
RUN npm install -g ts-node-dev

# npm update all
RUN npm i -g npm-check-updates

# nest
RUN npm install -g @nestjs/cli

# proto ts generate
RUN npm install -g ts-protoc-gen

RUN apk add protobuf